on:
  push:
    branches:
      - dev
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: checkout dev
        run: checkout dev

      - name: deploy
        run: npm run deploy
